services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    restart: unless-stopped

  frontend:
    image: ghcr.io/qiumatthew/website-frontend:latest
    expose:
      - "80"
    restart: unless-stopped

  # Future services:
  # api:
  #   image: ghcr.io/qiumatthew/website-api:latest
  #   expose:
  #     - "8000"
  #   env_file:
  #     - .env
  #   restart: unless-stopped